components/xx-rootmail.yaml

WIP for #13. Currently in it:
- Delegation zone with MX, DKIM and verification records
- Mail bucket and appropriate policies
- Website redirect configuration on the bucket to serve as zone delegation status health check (alarm missing)
- SES rule set creation for inbound mail handling and rule set activation

WIP - Root emails

---

README.md

Copied + comment proposal from gdocs.

Added non-technical documentation

---

components/rootmail.yaml

Fixed root mail generation bug

---

README.md
tests/pipeline.yaml

by having one s3 bucket and a subfolder for each branch

enable multi branch deployment

---

tests/setup-test-env.sh
tests/terminate-test-env.sh
tests/update-test-env.sh

this is the initial version of scripts to allow local testing with the [MAVM](https://github.com/superwerker/mavm/)

local testing with MAVM

---

components/budget.yaml
components/superwerker.yaml
docs/adrs/budget.md

This is the initial commit trying to close #24. Please review the general direction & then I'll contribute the ADR and integrate it into the main stack.

Added basic dynamic cost forecasting

---

glossary.md

Adding a glossary file is part of #74

docs: Add glossary file

---

components/guardduty.yaml
tests/tests.py

feat: Enable GD S3 data protection for existing and future member accounts

---

components/rootmail.yaml
tests/rootemails.py

Filter welcome and account-ready mails

---

tests/buildspec.yaml
tests/pipeline.yaml

This prepares for matrix tests which will be needed to test #23 
This change is actually a no-op but more regions other than eu-west-1 can be added to the text matrix later on.

Prepare for matrix tests

---

components/control-tower.yaml
components/guardduty.yaml
components/rootmail.yaml
components/security-hub.yaml
docs/adrs/rootmail.md
tests/buildspec.yaml
tests/rootemails.py
tests/setup-test-env.sh
tests/terminate-test-env.sh
tests/tests.py
tests/update-test-env.sh

Fix ses receive regions

---

tests/buildspec.yaml
tests/setup-test-env.sh
tests/update-test-env.sh

since no IAM roles are created with fixed names
this seems to be fallout from #23

remove obsolete NAMED_IAM capability

---

components/superwerker.yaml

Update description for installation process

---

docs/adrs/backup.md
templates/backup.yaml

by using Conformance Packs instead of StackSets to roll out Config rules and remediation.

work around aws config and stacksets race condition

---

templates/superwerker.template.yaml

since we believe it's best practice. and we are not sure that disabling worked anyway.

feat: make rootmail feature obligatory

---

templates/superwerker.template.yaml

chore: add quickstart id

---

templates/control-tower.yaml

fix(control-tower): work around aws ui timing issues by sleeping between steps

---

tests/update-test-env.sh

fix(update-test-env): fix wrong syntax for cloudformation deploy and parameter overrides

---

README.md

Included 1-click-installation video link. Could use some autoplay but it's too late for me to bother now.

Added installation video.

---

.releaserc

adapt to AWS quickstart scheme
fixes #151

chore(releases): correct releases page quick install links

---

templates/living-documentation.yaml

Related to #20, I updated the dashboard layout (old/new console UI) and extended the success-state with links to next topics.
**Deprecated**

Reformat dashboard

---

templates/living-documentation.yaml

this fixes #20 (Part of 1.1 milestone).
I had to make several formatting changes to python code in order to fit into 4096 CFN Lambda inline code limit.
TODO:

feat(living-documantion): provide living docs with next steps, SOPs and help

---

.github/workflows/release.yml
DEVELOPMENT.md

by switching to manually triggering the GitHub action.

chore(ci): have more control on release process

---

README.md

Created below changes in the readme file:
1. Added prerequisit on readme page 
2. Moved video and prerequisits as subsection of installation guide
3. Becky added steps shown in video
4. Added numbers instead of bullet points to features of this product.

Feedbackchange

---

README.md

Based on feedback by @KiranGosavi we need to highlight the installation paths.

Add more visible buttons for installation paths

---

README.md

I have added instructions to update superwerker to the readme. Please take a look and see if they are accurate.

How to update superwerker

---

tests/close-active-subaccounts/close-active-subaccounts.js
tests/close-active-subaccounts/package-lock.json
tests/close-active-subaccounts/package.json

by retrying account deletion which is flaky sometimes because puppeteer

tests: make teardown less flaky

---

tests/tests.py

since IAM might be eventually consistent here
hopefully fixes #152

try to work around security hub flaky test with sleep

---

tests/pipeline.yaml

Basics to separate versioned releases and branch deployments.
#137

chore: add new s3 bucket for releases

---

templates/backup.yaml
templates/budget.yaml
templates/control-tower.yaml
templates/guardduty.yaml
templates/living-documentation.yaml
templates/notifications.yaml
templates/rootmail.yaml
templates/security-hub.yaml
templates/service-control-policies.yaml

This merges downstream change https://github.com/aws-quickstart/quickstart-superwerker/pull/29 to upstream

Added Descriptions and QSIDs where needed.

---

tests/backup.py

by introducing waiting for table readiness before operating on the table

tests: make dynamodb backup tests more robust

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
templates/backup.yaml
templates/control-tower.yaml
templates/guardduty.yaml
templates/rootmail.yaml
templates/security-hub.yaml
templates/service-control-policies.yaml
tests/account-factory-wiring.yaml
tests/build.yaml
tests/pipeline.yaml

arns in template files should now be "partition agnostic" in accordance with the Quick Start linting requirements

Ensure happy linter

---

docs/adrs/control-tower.md
templates/control-tower.yaml

and also open up future possibilities as adding OUs, GuardRails etc by
using the awsapilib instead of CW Synthetics canaries
This also removes the broken update of existing CT installation (#238). This can be re-added later with awsapilib

feat(control-tower): make control tower setup more stable

---

tests/buildspec.yaml

in addition to a fresh install.

tests: test upgrade from latest release

---

templates/control-tower.yaml

since it still sometimes fails with CUSTOMER_ASSUME_ROLE_FAILED which indicates IAM eventual consistency errors

fix: more retries and waiting for setting up control tower

---

.github/workflows/lint.yml

tests: fix broken cfn-lint github action

---

README.md

- update the template link as it returned `access denied`
- also beautified the markdown with backticks for readability

docs(readme): fix update template link

---

.github/workflows/lint.yml

tests: revert to previous linter

---

tests/backup.py

tests: adapt to new IAM explicit deny message

---

.github/workflows/stale-issues-and-prs.yml

Keep issues with label "next"

---

tests/build.yaml

Post logs from CodeBuild to Github

---

tests/backup_test.py
tests/rootmail_test.py
tests/securityhub_test.py

Instead of using `time.sleep` use `retrying` lib.

fix: use retrying lib in all tests

---

DEVELOPMENT.md

Document in which AWS account the development takes place and how to get access.

docs: Document AWS account and access

---

cdk/src/stacks/guardduty.ts

Migrate guardduty stack to cdk

---

.github/workflows/pr-validation.yaml
.github/workflows/release.yml
tests/buildspec.yaml
tests/pipeline.yaml

ci: use GitHub OIDC for AWS credentials

---

.pre-commit-config.yaml
DEVELOPMENT.md
cdk/.husky/commit-msg
cdk/package.json
cdk/yarn.lock

to avoid folks from commiting with message which are not the commitizen standart.

feat: add commit hook validation with commitizen

---

cdk/Makefile
cdk/package.json
cdk/src/functions/notification_opsItem_created/Makefile
cdk/src/functions/python-tests.mk

test: include tests in yarn test

---

cdk/src/scripts/publish-assets.ts
tests/buildspec.yaml

fix: publish assets 

---

.github/workflows/pr-validation.yaml

fix for #388 as we needed the `yml` on `main`

fix: GH action manual trigger

---

.github/workflows/pr-validation.yaml

fix(ci): remove test steps and reactivate run codebuild

---

cdk/src/constructs/enable-controltower.ts
cdk/test/control-tower.test.ts

fix: rename resources to enable cleanup in upgrade

---

tests/pipeline.yaml

Disable web hook for CodePipeline.

ci: remove webhook for codepipeline

---

cdk/package.json
cdk/src/functions/living-docs-dashboard-generator.ts
cdk/src/stacks/living-documentation.ts
cdk/test/functions/living-docs-dashboard-generator.test.ts
cdk/test/living-documentation.test.ts
cdk/yarn.lock

Added changes from the previous branch for the living documentation dashboard.

build: added script for living documentation dashboard

---

cdk/cdk-bootstrap.py
cdk/src/scripts/publish-assets.ts

bucket has been created for publishing in eu-central-2
also, we should find a solution to the auto formation. maybe a git commit pre-hook?

feat: add eu-central-2 region for publishing

---

cdk/src/scripts/publish-assets.ts
cdk/superwerker-distribution/README.md
cdk/superwerker-distribution/cdk-bootstrap.py
scripts/ct+sso.sh
scripts/superwerker-regions.sh

Buckets for distribution have been created as well for the new regions

feat: add us-west-1 and ap-northeast-3 regions

---

cdk/.eslintrc.json
cdk/package.json
cdk/src/constructs/rootmail-hosted-zone-dkim-propagation.ts
cdk/src/constructs/rootmail-hosted-zone-dkim-verification-records.ts
cdk/src/index.ts
cdk/src/stacks/backup.ts
cdk/src/stacks/budget.ts
cdk/src/stacks/notifications.ts
cdk/src/stacks/rootmail.ts
cdk/src/stacks/security-hub.ts
cdk/src/stacks/sevice-control-policies.ts
cdk/test/functions/hosted-zone-dkim-propagation.is-complete-handler.test.ts
cdk/test/functions/hosted-zone-dkim-verification-records.on-event-handler.test.ts
cdk/yarn.lock
templates/backup.yaml
templates/security-hub.yaml
templates/service-control-policies.yaml

Also replaced deprecated rules from typescript-eslint, see https://typescript-eslint.io/blog/deprecating-formatting-rules/

feat: Integrate cdk nag

---

.github/workflows/pr-validation.yaml
templates/service-control-policies.yaml

this also fixes broken PR validation workflow due to missing AWS_REGION when instantiating boto3 client during test.

fix: remove redundant If statement in template file, cfn-lint finding
