components/rootmail.yaml
tests/pipeline.yaml
tests/rootemails.py

The plan would be to reference the lambda output in the parent stack and either override the email (e.g. for existing CT setups in the CT stack) or let the function generate them. By default it also verifies (while doing exponential backoffs) that the email delegation setup works.
As a followup I'd delete the obsolete healthcheck.

Added mail generator and verification function.

---

components/rootmail.yaml
tests/pipeline-dns-wiring.yaml
tests/pipeline.yaml

wire root domain once the nameserver delegation targets are set
this has to done asynchronously since the superwerker setup waits for it
so it cannot be done as part of the pipeline
fixes #64

wire rootmail dns delegation targets asynchronously in pipeline

---

components/rootmail.yaml
tests/close-active-subaccounts/.gitignore
tests/close-active-subaccounts/close-active-subaccounts.js
tests/close-active-subaccounts/package-lock.json
tests/close-active-subaccounts/package.json
tests/pipeline.yaml

Now that the OVM is wired in #57 we also need to remove the created sub-accounts after the test runs have finished. this PR automates the deletion of sub-accounts (currently: log-archive, audit, and one account factory account). it introduces the parsing of password reset emails, the link gets written to a temp SSM parameter which is picked up by the account deletion. this procedure could be used to automate other activities later on and/or create an OpsItem.

Remove subaccounts after each test run

---

components/superwerker.yaml
tests/pipeline-dns-wiring.yaml
tests/pipeline.yaml

by giving each run it's own subdomain (the vended aws account id)
this is another prerequisite for matrix tests as well

allow multiple parallel test environments

---

components/guardduty.yaml

Fixes #84 by giving the delegated admin time to settle. I could not find a better solution than waiting/sleeping.

Fix guardduty setup

---

tests/rootemails.py

by using get_ops_summary instead of describe_ops_items with 'contains' filter.
Apparently 'contains' filter did not filter out other mails properly.
fixes #105

fix rootmail tests

---

components/rootmail.yaml

fix: make rootmail stackset exec role only assumable from admin role

---

tests/buildspec.yaml

to prevent "An error occurred (UnrecognizedClientException) when calling the DisableSecurityHub operation: The security token included in the request is invalid."

Refresh AWS CLI credentials before running tests

---

docs/adrs/rootmail.md
templates/living-documentation.yaml
templates/rootmail.yaml
templates/superwerker.template.yaml
tests/buildspec.yaml
tests/rootmail.py
tests/rootmails.py

fixes #121
I decided to use "RootMail" because it was already used more often than any other variant.

fix: unified rootmail wording

---

templates/backup.yaml

since depending on the Lambda without trigger does not seem to be sufficient
hopefully fixes #145

fix(backup): depend on trigger/event instead of only the pure Lambda

---

templates/control-tower.yaml

by accepting the cookie banner if present. otherwise button would be overlapped by the cookie banner so pupeteers fails clicking through the setup process
fixes #162

fix(control-tower): fix control tower setup

---

DEVELOPMENT.md
tests/build.yaml
tests/start-build.sh

by providing a codebuild job, a helper script, and a primitive howto for
making it possible to re-use the same test infrastructure (MAVM) as used
in the main pipeline.
(the howto still has many missing docs, but this is not in scope here)
this is the first step for #136

make it possible to get feedback earlier than pushing to `main`

---

templates/living-documentation.yaml

The CW alarm event-driven invocation of the generator Lambda would be
too late since it triggers when the alarm is green.
So we move from event based trigger to scheduler every minute, which is
still covered by Lambda free tier and frees us from timing pains.
There might be still some gap between initial creation of the RootMail
alarm and the first call of the dashboard generator Lambda which would
result in exceptions in the generator Lambda. This was a deliberate
tradeoff.
fixes #153

fix(living-documentation): generate dashboard immediately after creation

---

templates/control-tower.yaml

in order to prevent deprecated canary version from failing, it wont work anymore from end of may on.
fixes #202

fix(control-tower): upgrade to latest CW Synthetics version

---

templates/service-control-policies.yaml

Current, the superwerker SCP is called `ServiceControlPolicy` as the logical ID in CloudFormation. This is confusing when using the AWS Organizations UI.
I renamed it to `superwerker`
cc @tillkahlbrock

feat: rename SCP from "ServiceControlPolicy" into "superwerker"

---

tests/buildspec.yaml

by running CloudFormation and tests with an IAM user with static credentials
and without a security token

tests: circumvent `The security token included in the request is invalid` errors

---

templates/service-control-policies.yaml

Added condition to check if both features are set before creating resouce.

fix: ServiceControlPolicies feature should not fail if neither SecurityHub nor Backup feature are enabled

---

templates/superwerker.template.yaml

References to control tower as an optional parameter are removed from superwerker.template.yaml

fix(control-tower): remove feature flag since Control Tower is a mandatory feature

---

tests/build.yaml

and make skipping ci/PR tests the exception.
this also hopefully leads to cleaner commit histories without meaningless "[CodeBuild]" commits.

tests: make running tests the default

---

templates/control-tower.yaml
tests/account-factory-wiring.yaml

It appears that the setup control tower event is triggered before the landing zone is completed, therefore the workaround starts too early and the subaccount creation for the tests fails. We are trying to prevent the control tower workaround from triggering too early by moving the workaround code into the tests.

tests: fix broken pipeline

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

We don't have ADRs for logging and integrity protection, so remove the misleading checklist items.

docs: remove misleading links to non existant ADRs in PR template checklist items

---

tests/buildspec.yaml

Sometimes, in Pull Requests, a branch reference might be already deleted
on GitHub, probably due to force pushes on feature branches. Then the
cleanup CodeBuild fails with
```
reference not found for primary source and source version ...
```
To work around this, always call the cleanup CodeBuild from the default
`main` branch. This change will result in the `buildspec-cleanup.yaml`
always being used from the `main` branch, not a feature branch.

tests: avoid broken cleanup due to nonexisting git references

---

templates/backup.yaml

- more robust against UI changes
- works also when CFN Service_Managed Stack Sets are already enabled

fix: make backup stack more resilient by using awsapilib instead of CWS canaries

---

templates/backup.yaml

by giving the Lambda function more time since it installs dependencies
on the fly

fix(backup): reduce timeout errors

---

README.md

I ran into an issue when updating from `0.12.x` to `0.13.x` because we renamed the deployment/release bucket. The existing parameters had `QSS3BucketName` set to `superwerker-deployments` and at some point we changed the bucket to `superwerker-releases`.
With the incorrect bucket name, CloudFormation failed to update the stack:
```
S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
```

Extend update steps in README.md

---

templates/control-tower.yaml

by using awsapilib version which adapts to native Control Tower APIs
It uses the current WIP branch with working `tower.deploy()` function -> https://github.com/schubergphilis/awsapilib/pull/30/ 
fixes #298

fix: fix Control Tower rollout

---

.github/workflows/stale-issues-and-prs.yml

Close stale issues after 60 days and 5 days of inactivity. Issues labeled with "someday" or issues associated with a milestone won't be touched. Only run in dry run mode for now, check if results are OK.

Close stale issues automatically

---

tests/account-factory-wiring.yaml

#336: Fixed latest version of `syn-nodejs-pupeteer` to 3.7

chore: change to latest syn-nodejs-puppeteer-3.8

---

tests/requirements.txt
tests/requirements_local.txt

using virtualenv means we have to install all dependencies into the virtualenv, including boto3.

fix: add boto3 to requirements.txt

---

README.md
cdk/src/stacks/superwerker.ts
tests/buildspec.yaml
tests/update-test-env.sh

We don't need these anymore because CDK assets solve the multiple stacks problem for us.
Also this will fix [this error](https://github.com/aws-quickstart/quickstart-superwerker/pull/37/checks?check_run_id=11058790327).

chore: Remove obsolete Quickstart S3 prefixes

---

.github/workflows/pr-validation.yaml

This PR increases the codebuild session duration 2 hours, as it tends to run relatively long. This way, gh-actions will not receive a timeout during the build, hopefully.
See also: https://github.com/aws-actions/configure-aws-credentials#assuming-a-role

ci: increase AWS session duration to 2 hours for codebuild run

---

.github/dependabot.yml

This PR defines a group in the `dependabot` configuration intended to upgrade all `@aws-sdk/*` dependencies together. The intention is to avoid `dependabot` creating many small pull requests for `aws-sdk` components that should all match the same version number.

chore: group aws-sdk dependencies in dependabot

---

.github/dependabot.yml

This PR groups development dependencies in dependabot in order to consolidate generated PRs for lower risk dev upgrades.
Also experimentally updates the number of PRs dependabot is allowed to open to 10 to avoid errors in the dependabot logs:
https://github.com/superwerker/superwerker/network/updates

chore: group development dependencies in dependabot

---

.github/dependabot.yml

This PR targets only `minor` and `patch` updates according to semantic versioning `major.minor.patch` for the development dependencies when managed by dependabot.

chore: target only minor and patch version updates for dependabot development group

---

.github/workflows/pr-validation.yaml
templates/service-control-policies.yaml

cnf lint reported: 
`W1028 ['Fn::If', 2] is not reachable. When setting condition 'IncludeBackup' to False from current status True
templates/service-control-policies.yaml:63:19`
due to a the extra If statement inside the SCPBaseline. Because the resource only instantiates if the **IncludeBackup** condition is true, the extra condition inside the Statements is obsolete.

fix: Remove redundant if, cfn-lint finding

---

tests/rootmail_test.py
tests/securityhub_test.py

Acceptance tests were broken due to bit rotting.

fix: broken acceptance tests
